Repository ss14-boxstation/ss14-boxstation, pull requests merged in 2025-09, with the labels that each got.

#24 Adds the Supply Assistant, a Cargo Learner Role
  Resources/Locale/en-US/_Box/job/job-description.ftl
  Resources/Locale/en-US/_Box/job/job-names.ftl
  Resources/Locale/en-US/_Box/job/job-supervisors.ftl
  Resources/Locale/en-US/_Box/preferences/loadout-groups.ftl
  Resources/Prototypes/Loadouts/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Maps/amber.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/Maps/exo.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/oasis.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/plasma.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_Box/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/_Box/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/_Box/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/_Box/Loadouts/Jobs/Cargo/supply_assistant.yml
  Resources/Prototypes/_Box/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Box/Loadouts/role_loadouts.yml
  Resources/Prototypes/_Box/Maps/Modifications/amber.yml
  Resources/Prototypes/_Box/Maps/Modifications/aspid.yml
  Resources/Prototypes/_Box/Maps/Modifications/athena.yml
  Resources/Prototypes/_Box/Maps/Modifications/atlas.yml
  Resources/Prototypes/_Box/Maps/Modifications/bagel.yml
  Resources/Prototypes/_Box/Maps/Modifications/barratry.yml
  Resources/Prototypes/_Box/Maps/Modifications/box.yml
  Resources/Prototypes/_Box/Maps/Modifications/elkridge.yml
  Resources/Prototypes/_Box/Maps/Modifications/exo.yml
  Resources/Prototypes/_Box/Maps/Modifications/fland.yml
  Resources/Prototypes/_Box/Maps/Modifications/marathon.yml
  Resources/Prototypes/_Box/Maps/Modifications/mira.yml
  Resources/Prototypes/_Box/Maps/Modifications/oasis.yml
  Resources/Prototypes/_Box/Maps/Modifications/omega.yml
  Resources/Prototypes/_Box/Maps/Modifications/packed.yml
  Resources/Prototypes/_Box/Maps/Modifications/plasma.yml
  Resources/Prototypes/_Box/Maps/Modifications/prime.yml
  Resources/Prototypes/_Box/Maps/omega.yml
  Resources/Prototypes/_Box/Roles/Jobs/Cargo/supply_assistant.yml
  Resources/Prototypes/_Box/Roles/play_time_trackers.yml
  Resources/Prototypes/_Box/StatusIcon/job.yml
  Resources/Prototypes/_Harmony/Maps/aspid.yml
  Resources/Prototypes/_Harmony/Maps/athena.yml
  Resources/Prototypes/_Harmony/Maps/atlas.yml
  Resources/Prototypes/_Harmony/Maps/barratry.yml
  Resources/Prototypes/_Harmony/Maps/mira.yml
  Resources/Prototypes/_Harmony/Maps/prime.yml
  Resources/Textures/_Box/Interface/Misc/job_icons.rsi/SupplyAssistant.png
  Resources/Textures/_Box/Interface/Misc/job_icons.rsi/meta.json
  Resources/Textures/_Box/Markers/job.rsi/meta.json
  Resources/Textures/_Box/Markers/job.rsi/supplyassistant.png
  Resources/Textures/_Box/Objects/Devices/pda.rsi/meta.json
  Resources/Textures/_Box/Objects/Devices/pda.rsi/pda-interncargo.png
  Resources/Textures/_Box/Objects/Misc/id_cards.rsi/idintern-cargo.png
  Resources/Textures/_Box/Objects/Misc/id_cards.rsi/meta.json
Labels: S: Untriaged, S: Needs Review, Changes: Sprites, Changes: Map

#25 Updates Job Playtime Requirements
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
Labels: S: Approved

#29 Changelog fix
  Resources/Changelog/Box.yml
  Resources/Locale/en-US/_Box/changelog/changelog-window.ftl
Labels: Maintenance

#27 IPC Topical Remaster - Part 1 (Basic Topicals)
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Entities/Objects/Tools/welders.yml
  Resources/Prototypes/_Box/Catalog/Fills/Items/firstaidkits.yml
  Resources/Prototypes/_DV/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/_Harmony/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/_Harmony/Recipes/Lathes/lathepacks.yml
Labels: S: Approved

#31 FIX: Prevent testfail due to IPCs
  Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs
Labels: S: Untriaged, S: Needs Review, Changes: C#

#23 Ports Syndiroaches From Goob
  Resources/Locale/en-US/_Goobstation/ghost/ghost-role-component.ftl
  Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
  Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
  Resources/Prototypes/_Goobstation/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/0-equipped-HELMET.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/icon.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/inhand-left.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/inhand-right.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/meta.json
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/mothroach-moving.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/mothroach.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/mothroach_dead.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/mothroach_lazy.png
  Resources/Textures/_Goobstation/Mobs/Animals/syndiroach.rsi/mothroach_sleep.png
  Resources/Textures/_Harmony/Objects/Devices/communication.rsi/meta.json
  Resources/Textures/_Harmony/Objects/Devices/communication.rsi/old-radio-syndiroach.png
Labels: S: Approved

#36 IPC Chems
  Content.Server/Body/Components/MetabolizerComponent.cs
  Content.Server/Body/Systems/MetabolizerSystem.cs
  Content.Shared/_EE/Silicon/Components/SiliconComponent.cs
  Resources/Locale/en-US/_Box/armor/armor-examine.ftl
  Resources/Locale/en-US/_Box/damage/damage-types.ftl
  Resources/Locale/en-US/_Box/flavors/flavor-profiles.ftl
  Resources/Locale/en-US/_Box/metabolism/metabolism-groups.ftl
  Resources/Locale/en-US/_Box/metabolism/metabolizer-types.ftl
  Resources/Locale/en-US/_Box/reagents/meta/chemicals.ftl
  Resources/Locale/en-US/_Box/reagents/meta/chemicals_synthetic.ftl
  Resources/Locale/en-US/_Box/reagents/meta/fun_synthetic.ftl
  Resources/Locale/en-US/_Box/reagents/meta/medicine_synthetic.ftl
  Resources/Locale/en-US/_Box/reagents/meta/toxins.ftl
  Resources/Locale/en-US/_Box/reagents/meta/toxins_synthetic.ftl
  Resources/Prototypes/Body/Organs/arachnid.yml
  Resources/Prototypes/Body/Organs/human.yml
  Resources/Prototypes/Damage/containers.yml
  Resources/Prototypes/Damage/groups.yml
  Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
  Resources/Prototypes/Entities/Objects/Misc/implanters.yml
  Resources/Prototypes/Reagents/biological.yml
  Resources/Prototypes/Reagents/chemicals.yml
  Resources/Prototypes/Reagents/cleaning.yml
  Resources/Prototypes/Reagents/elements.yml
  Resources/Prototypes/Reagents/fun.yml
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Reagents/pyrotechnic.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Prototypes/_Box/Chemistry/metabolism_groups.yml
  Resources/Prototypes/_Box/Chemistry/metabolizer_types.yml
  Resources/Prototypes/_Box/Damage/types.yml
  Resources/Prototypes/_Box/Flavors/flavors.yml
  Resources/Prototypes/_Box/Reagents/chemicals.yml
  Resources/Prototypes/_Box/Reagents/chemicals_synthetic.yml
  Resources/Prototypes/_Box/Reagents/fun_synthetic.yml
  Resources/Prototypes/_Box/Reagents/medicine_synthetic.yml
  Resources/Prototypes/_Box/Reagents/toxins.yml
  Resources/Prototypes/_Box/Reagents/toxins_synthetic.yml
  Resources/Prototypes/_Box/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/_Box/Recipes/Reactions/chemicals_synthetic.yml
  Resources/Prototypes/_Box/Recipes/Reactions/fun_synthetic.yml
  Resources/Prototypes/_Box/Recipes/Reactions/medicine_synthetic.yml
  Resources/Prototypes/_Box/Recipes/Reactions/toxins.yml
  Resources/Prototypes/_Box/Recipes/Reactions/toxins_synthetic.yml
  Resources/Prototypes/_Box/tags.yml
  Resources/Prototypes/_DV/Damage/containers.yml
  Resources/Prototypes/_DV/Damage/modifier_sets.yml
  Resources/Prototypes/_EE/Body/Organs/ipc.yml
  Resources/Prototypes/_EE/Body/Prototypes/ipc.yml
  Resources/Prototypes/_EE/Entities/Mobs/Player/silicon_base.yml
  Resources/Prototypes/_EE/InventoryTemplates/ipc_inventory_template.yml
  Resources/Prototypes/_Harmony/Reagents/chemicals.yml
  Resources/Textures/_Box/Mobs/Species/IPC/organs.rsi/ipc-brain-off.png
  Resources/Textures/_Box/Mobs/Species/IPC/organs.rsi/ipc-brain-on.png
  Resources/Textures/_Box/Mobs/Species/IPC/organs.rsi/ipc-stomach.png
  Resources/Textures/_Box/Mobs/Species/IPC/organs.rsi/meta.json
Labels: S: Needs Review, Changes: Sprites, Changes: C#
