Repository ss14-boxstation/ss14-boxstation, pull requests merged in 2025-08, with the labels that each got.

#13 Ports (Updated) Omega
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/_Box/omega.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/_Box/Guidebook/Maps/omega.yml
Labels: S: Untriaged, S: Needs Review

#14 tweak: Reduce IPC battery drain rate
  Resources/Prototypes/_EE/Entities/Mobs/Player/ipc.yml
Labels: S: Untriaged, S: Needs Review

#17 Adds Scarfs And Pride Scarfs To Trinkets
  Resources/Locale/en-US/_Box/preferences/loadout-groups.ftl
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Box/Loadouts/Miscellaneous/trinkets.yml
  Resources/Prototypes/_Box/Loadouts/loadout_groups.yml
Labels: S: Approved

#18 IPC Medbay Interaction Tweaks
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
  Resources/Prototypes/_Box/Catalog/Fills/Items/firstaidkits.yml
  Resources/Prototypes/_Box/Entities/Objects/Specific/Medical/medkits.yml
  Resources/Prototypes/_Box/tags.yml
  Resources/Prototypes/_DV/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/_Harmony/Catalog/Fills/Crates/medical.yml
  Resources/Prototypes/_Harmony/Entities/Objects/Specific/Medical/healing.yml
  Resources/Textures/_Box/Objects/Specific/Medical/advipcmedkit.rsi/meta.json
  Resources/Textures/_Box/Objects/Specific/Medical/advipcmedkit.rsi/siliconkit-inhand-left.png
  Resources/Textures/_Box/Objects/Specific/Medical/advipcmedkit.rsi/siliconkit-inhand-right.png
  Resources/Textures/_Box/Objects/Specific/Medical/advipcmedkit.rsi/siliconkit.png
  Resources/Textures/_starcup/Objects/Specific/Medical/firstaidkits.rsi/meta.json
  Resources/Textures/_starcup/Objects/Specific/Medical/firstaidkits.rsi/siliconkit-inhand-left.png
  Resources/Textures/_starcup/Objects/Specific/Medical/firstaidkits.rsi/siliconkit-inhand-right.png
  Resources/Textures/_starcup/Objects/Specific/Medical/firstaidkits.rsi/siliconkit.png
Labels: S: Approved, Changes: Sprites

#19 Fixes IPCs Crawling
  Resources/Prototypes/_EE/Entities/Mobs/Player/silicon_base.yml
Labels: S: Untriaged, S: Needs Review

#20 Removes the random character setting for the dev environment
  Resources/ConfigPresets/Build/development.toml
Labels: S: Untriaged, S: Needs Review

#21 Major Tweaks to IPC bloodstream and surrounding systems
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/_Box/Catalog/Fills/Items/firstaidkits.yml
  Resources/Prototypes/_EE/Entities/Mobs/Player/silicon_base.yml
  Resources/Prototypes/_Harmony/Catalog/Fills/Crates/medical.yml
  Resources/Prototypes/_Harmony/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/_Harmony/Recipes/Cooking/medical_recipes.yml
Labels: S: Untriaged, S: Needs Review
